// GENERATED by tools/check_sprites.py --emit. Do not edit.
//
// Species SpriteCollab has no art for at all. They KEEP THEIR DEX
// NUMBERS -- removing one would renumber every species after it, and
// dex numbers are positional in saved data (dexReg bits, speciesId,
// every party record) -- but they are kept out of the egg pool, since
// hatching one gives a creature that can only ever draw as a number.
//
// Re-run after any expansion, and again if upstream adds art.
#pragma once

#define NO_ART_COUNT 48
static const int16_t NO_ART[NO_ART_COUNT ? NO_ART_COUNT : 1] = {
  514, 516, 520, 522, 523, 538, 558, 564, 565, 591, 592, 616, 626, 668, 732, 735, 741, 756, 765, 837, 838, 839, 847, 866, 870, 878, 893, 896, 931, 942, 943, 944, 947, 949, 950, 954, 956, 962, 973, 986, 993, 999, 1001, 1002, 1008, 1014, 1022, 1023
};

static inline bool speciesHasArt(int16_t d) {
  for (int i = 0; i < NO_ART_COUNT; i++)
    if (NO_ART[i] == d) return false;
  return true;
}
